title: Андрей Цветков
tagline: архитектор программного обеспечения
email: ts.andrey@gmail.com
description: > 
  Андрей Цветков, архитектор ПО
baseurl: "" 
url: "https://AndreyTsvetkov.github.io/" 
#twitter_username: jekyllrb
github_username:  AndreyTsvetkov  


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
