title: Andrey Tsvetkov
tagline: Software architect
email: ts.andrey@gmail.com
description: > 
  Andrey Tsvetkov, the software developer
baseurl: "" 
url: "https://AndreyTsvetkov.github.io/" 
#twitter_username: jekyllrb
github_username:  AndreyTsvetkov  


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
